export const agentsData = [
  {
    identificationNumber: "AGT-001",
    fullName: "Koffi Mensah",
    phoneNumber: "90 11 22 33",
    email: "koffi.mensah@essivivi.com",
    assignedTricycle: "Tri-001",
    status: "En tournée",
    hireDate: "2024-01-15",
  },
  {
    identificationNumber: "AGT-002",
    fullName: "Jean Dupont",
    phoneNumber: "91 22 33 44",
    email: "jean.dupont@essivivi.com",
    assignedTricycle: "Tri-002",
    status: "Actif",
    hireDate: "2024-02-01",
  },
  {
    identificationNumber: "AGT-003",
    fullName: "Ami Diallo",
    phoneNumber: "92 33 44 55",
    email: "ami.diallo@essivivi.com",
    assignedTricycle: "Tri-003",
    status: "Inactif",
    hireDate: "2023-11-20",
  },
  {
    identificationNumber: "AGT-004",
    fullName: "Kodjo Toussaint",
    phoneNumber: "93 44 55 66",
    email: "kodjo.toussaint@essivivi.com",
    assignedTricycle: "Tri-004",
    status: "En tournée",
    hireDate: "2024-03-10",
  },
  {
    identificationNumber: "AGT-005",
    fullName: "Sarah Lane",
    phoneNumber: "94 55 66 77",
    email: "sarah.lane@essivivi.com",
    assignedTricycle: "N/A",
    status: "Actif",
    hireDate: "2023-12-05",
  },
];
